media:
  input: 
  output: src/assets/images

# .pages.yml

media:
  # Ảnh “cover” dùng frontmatter image() của Astro → phải nằm trong src/
  - name: astro_images
    label: Astro Images (src)
    input: src/assets/images
    output: src/assets/images  # URL sẽ chèn vào nội dung nếu có dùng config này

  # Ảnh chèn trong body → để public phục vụ thẳng ở /images
  - name: public_images
    label: Public Images
    input: src/assets/images
    output: src/assets/images


content:
  - name: blogs
    label: Blogs
    type: collection
    path: "src/content/blogs"
    filename: "{year}-{month}-{day}-{fields.title}.md"  # đổi .mdx nếu bạn dùng MDX
    view:
      fields: [title, draft, pubDate, author, tags]
      default:
        sort: pubDate
        order: desc

    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: description
        label: Description
        type: text
        required: true

      - name: pubDate
        label: Publication Date
        type: date
        required: true
        options:
          format: yyyy-MM-dd
          time: false

      - name: author
        label: Author
        type: string
        required: false

      - name: tags
        label: Tags
        type: string
        required: false
        

      - name: draft
        label: Draft
        type: boolean
        default: false

      - name: image
        label: Cover Image
        type: object
        required: false
        fields:
          - name: url
            label: Image file
            type: image
            path: "src/assets/images"
            required: true
            extensions: [jpg, jpeg, png, webp, gif, svg]
          - name: alt
            label: Alt text
            type: string
            required: false
      - name: body
        label: Body
        type: rich-text
        required: false
        options:
            media: public_images
            path: src/assets/images
            extensions: [jpg, jpeg, png, webp, gif, svg]